### PR TITLE
Add geos section, close #2

### LINKED ISSUE #2: Add section on `geos`

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @paleolimbot, as developer of `geos`, your quick sanity check/quickfire review here would be most appreciated.

Surprise for me was having to call `geos_make_collection()` before the union, am I missing anything?

Also, would you be interested in a vignette at some point? May give that a bash after teaching this at OpenGeoHub!

**Comment by Robinlovelace** [comment]
Going to merge now to check it renders OK with actions. Post merge review or any comments very, very welcome :pray:

**Comment by kadyb** [comment]
Great topic! I think it's worth pointing out that `{geos}` is not only faster, but also allocates less memory (at least according to `bechn::mark()`) and the representation of objects in the environment takes up less memory compared to `{sf}` ([here](https://kadyb.github.io/geotips/html/03_vector_operations.html) I did small comparison recently). Maybe at some stage it is worth mentioning the tools for fast processing of data frames, i.e. `{data.table}` and `{collapse}` ([vignette](https://sebkrantz.github.io/collapse/articles/collapse_and_sf.html))?

**Comment by Robinlovelace** [comment]
> Maybe at some stage it is worth mentioning the tools for fast processing of data frames, i.e. `{data.table}` and `{collapse}` ([vignette](https://sebkrantz.github.io/collapse/articles/collapse_and_sf.html))?

Many thanks @kadyb. Agreed, in scope for this practical session and I plan to add something on collapse (above `data.table`, although let me know if you think I should go with `data.table` as a more established pkg).

**Comment by JosiahParry** [comment]
`collapse` looks interesting. The syntax seems better than `data.table` but not as ergonomic as `dplyr()`—e.g. drop = TRUE by default.

One of the noticeable difference with geos and sf is that sf stores geometry as a list of R types meaning that it has to serialize that data to geos / s2 whenever it does a manipulation on them. geos stores a list of pointers to C geos types meaning that there is no serialization or deserialization that occurs.

**Comment by kadyb** [comment]
> One of the noticeable difference with geos and sf is that sf stores geometry as a list of R types meaning that it has to serialize that data to geos / s2 whenever it does a manipulation on them. geos stores a list of pointers to C geos types meaning that there is no serialization or deserialization that occurs.

So in the end, the `sf` and `geos` objects take a similar memory in the system? The difference is that `object.size()` (and `bench::mark()`) don't report the memory occupied by the C++ pointer.

**Comment by JosiahParry** [comment]
I don't know if that's the case or not. The memory occupies by an R list might be different than that of the corresponding C struct pointer. All I know is that sfc objects are stored as a list with each feature being stored as a double, matrix, or list of matrices. Then, to use those geometries by geos or s2, the R objects need to be converted to those C structs, worked on, then converted _back_ to R lists—which is a lot of overhead!

**Comment by kadyb** [comment]
Let's wait for @paleolimbot answer, because after your comment, I think my example (and what I wrote before) about memory usage is misleading:

```r
library("sf")
library("geos")
set.seed(1)

n = 1000
df = data.frame(x = rnorm(n), y = rnorm(n))
pts_sf = st_as_sf(df, coords = c("x", "y"))
pts_sf = st_as_sfc(pts_sf)
pts_geos = as_geos_geometry(pts_sf)

sf = st_buffer(pts_sf, 50, nQuadSegs = 30)
format(object.size(sf), units = "auto")
#> [1] "2.5 Mb"

geos = geos_buffer(pts_geos, 50, params = geos_buffer_params(quad_segs = 30))
format(object.size(geos), units = "auto")
#> [1] "71.4 Kb"
```

**Pull request merged**
